<?php
define('LOCAL_LANG', 'ru');
define('LOCAL_APP_DESCRIPTION', 'Приложение для чтения романов, повестей и рассказов.');
define('LOCAL_CHOOSE_A_STORY', 'Выберите историю для чтения');
define('LOCAL_ALL_STORIES', 'Все истории');
define('LOCAL_MORE_INFO', 'Подробнее');
define('LOCAL_STORY_WEBSITE', 'Посетить сайт истории');
define('LOCAL_TOGGLE_BW', 'Переключить тёмный/светлый');
define('LOCAL_FIRST', 'В начало');
define('LOCAL_PREVIOUS', 'Назад');
define('LOCAL_NEXT', 'Вперёд');
define('LOCAL_LAST', 'В конец');
define('LOCAL_ALL_CHAPTERS', 'Все сразу');
define('LOCAL_CHAPTER_GO_TO', '— Перейти к главе —');
define('LOCAL_STORY_NOT_FOUND', 'Рассказ не найден');
define('LOCAL_CHAPTER_NOT_EXIST', 'Глава не найдена!');
define('LOCAL_FONT_DECREASE', 'Уменьшить шрифт');
define('LOCAL_FONT_INCREASE', 'Увеличить шрифт');
define('LOCAL_FONT_DECREASE_TXT', 'A-');
define('LOCAL_FONT_INCREASE_TXT', 'A+');
